server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # Misol tariqasida marshrutlar. O'zingiznikiga qarab moslab olasiz
      routes:
        - id: tour-agency
          uri: lb://tour-agency
          predicates:
            - Path=/api/v1/**
        - id: asistent-service
          uri: lb://asistent-service
          predicates:
            - Path=/assistant/**
  security:
    jwt:
      access-key: TourAgencyVeryveryLongAccessSecretkeyForJwtTokenGeneRationAndValidatiOnYouCanchangeItButYouCanFindThissecretKey

  zipkin:
    sender:
      type: web

management:
  endpoints:
    web:
      exposure:
        include: refresh
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      connect-timeout: 1s
      read-timeout: 10s
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"