server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/touragency
    username: quvoncuz
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  security:
    jwt:
      access-key: TourAgencyVeryveryLongAccessSecretkeyForJwtTokenGeneRationAndValidatiOnYouCanchangeItButYouCanFindThissecretKey

  zipkin:
    sender:
      type: web

management:
  endpoints:
    web:
      exposure:
        include: refresh
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    context-propagation:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      connect-timeout: 1s
      read-timeout: 10s

resilience4j:
  circuitbreaker:
    instances:
      asistent-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      asistent-service:
        timeout-duration: 3s
  retry:
    instances:
      asistent-service:
        max-attempts: 3
        wait-duration: 1s

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

click:
  base-url: https://my.click.uz/services/pay
  service-id: 123
  merchant-id: 123
  secret-key: mc_