server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: tour-agency
            uri: lb://tour-agency
            predicates:
              - Path=/api/v1/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/